In [4]:
x = 1
while x < 10:
    print('Цикл выполнился',x,"раз(а)")
    x += 1


Цикл выполнился 1 раз(а)
Цикл выполнился 2 раз(а)
Цикл выполнился 3 раз(а)
Цикл выполнился 4 раз(а)
Цикл выполнился 5 раз(а)
Цикл выполнился 6 раз(а)
Цикл выполнился 7 раз(а)
Цикл выполнился 8 раз(а)
Цикл выполнился 9 раз(а)


In [8]:
x = 1
while x < 10:
    if x == 5:
        break
    x += 1
print(x)

5


In [9]:
x = 1
while x < 10:
    x += 1
    if x % 2 ==0:
        continue
    print(x)

3
5
7
9


In [3]:
while 1 == 0:
    print("Ty LOX")
else: print("ty ne lox")

ty ne lox


In [5]:
def yell (text):
    return text.upper() + "!"
bark = yell
bark("woof")

'WOOF!'

In [8]:
def yell (text):
    return text.upper() + "!"
bark = yell
del yell # удаление функции
bark("woof")

'WOOF!'

In [22]:
def fctrl (n):
    if not isinstance(n, int):
        raise TypeError("Число не является целым")
    if n <= 1:
        raise TypeError("Число не должно быть отрицательным")
    def i_fctrl (n):
        if n <= 1:
            return 1
        return n * i_fctrl(n-1)
    return i_fctrl(n)
print(fctrl(n))

TypeError: Число не должно быть отрицательным

In [37]:
def say_hello(name):
    print(f"Hello, {name}")           #  print("Hello, " + name)  # одинаковые записи, но 1ый вариант удобнее
say_hello("Valery")

Hello, valery


In [35]:
a = 5
b = 10
print(f"Hello, a+b = {a+b}")

Hello, a+b = 15


In [40]:
def say_hello(name="Valery"):
    print(f"Hello, {name}")           #  print("Hello, " + name)  # одинаковые записи, но 1ый вариант удобнее
say_hello()

Hello, Valery


In [42]:
def print_person(name, * , age, company):      #    нужно указывать age и company
    print(f"Name: {name}, Age: {age}, Company: {company}")
print_person("Bob", age = 26, company="Mic")

Name: Bob, Age: 26, Company: Mic


In [44]:
def print_person(name, / , age, company="apple"):      #    в любом порядке
    print(f"Name: {name}, Age: {age}, Company: {company}")
print_person("Bob",  company="Mic", age = 26)

Name: Bob, Age: 26, Company: Mic


In [48]:
def sum(*numbers):     # * для любого количества numbers
    result = 0
    for n in numbers:
        result += n
    print(f"sum = {result}")
sum(1, 2, 4, 5, 10)

sum = 22


In [50]:
line = ['jil', 'yrrtb', 're4e5eb']
max(line, key=len)

're4e5eb'

In [59]:
import math
math.trunc(11.1)
math.exp(3)
math.expm1(3)        #     exp - 1
math.log(16,4)
math.log2(3)
math.log10(2)
math.log(3)          # ln
math.sqrt(4)


2.0

In [61]:
from math import sqrt
sqrt(4)

2.0

In [63]:
print(math.e, math.pi)

2.718281828459045 3.141592653589793


In [65]:
from statistics import mean
print(mean([1,2,3,4]))

2.5


In [68]:
import statistics
statistics.mode([1,2,3,3,4])

3

In [70]:
statistics.multimode('eg33vr5344qiuu34g9qigowgshdushagwugsahhg')

['g']

In [72]:
statistics.multimode('aaaabbbbrngpwd')

['a', 'b']

In [85]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)


[1 2 3 4 5]


In [87]:
import numpy as np
arr = np.array(1)
print(arr)

1


In [91]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(arr.ndim)
print(arr.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2
(2, 5)


In [92]:
import numpy as np
r_arr = np.random.randint(-5,10, randomesize)

NameError: name 'randomesize' is not defined

In [96]:
arr = np.ones((2,2))
print (arr)

[[1. 1.]
 [1. 1.]]


In [97]:
arr = np.full((2,2),4)
print(arr)

[[4 4]
 [4 4]]


In [99]:
arr = np.identity(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [105]:
arr = np.identity(4, dtype='int32')
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [107]:
arr = np.identity(4, dtype='float64')
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [109]:
arr = np.identity(2, dtype='int32')
print(arr)

[[1 0]
 [0 1]]


In [111]:
arr = np.array([1,2,3,4])
print(arr+2)

[3 4 5 6]


In [114]:
arr = np.array([1,2,3,4])
arr2 = np.array([1,2,3,4])
print(arr+arr2)

[ 1  4  9 16]


In [116]:
arr = np.array([1,2,3,4])
print(np.cos(arr))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [119]:
arr1 = np.ones((2,3))
arr2 = np.full((3,2),2)
print(np.matmul(arr1,arr2))

[[6. 6.]
 [6. 6.]]


In [123]:
arr = np.array([[1,2,3],[4,5,6]])
total_sum = arr.sum()
print(total_sum)
sum_along_axis0 = arr.sum(axis0)
print(sum_along_asix0)

21


NameError: name 'sum_along_asix0' is not defined

In [128]:
arr = np.array([[1,2,3],[4,5,6]])
arr2 = arr.reshape(3,2)
print(arr2)

[[1 2]
 [3 4]
 [5 6]]
